### ISSUE TITLE
Add repository layer in your example

### ISSUE THREAD

**Issue by Michenux** [Nimrodda/dagger-androidinjector#3]
Hi,

It would be great to see a repository layer managed by dagger in your example.
The FeaturePresenter would use an ObjectRepository to fetch data.
ObjectRepository would be singleton.

Best regards
Laurent

**Comment by Nimrodda** [comment]
Well, there's already something that resembles a repository - class named `SomeService`. I can rename it to `FooRepository` or something like that though I'd advice against scoping anything with Singleton. Check out https://medium.com/square-corner-blog/keeping-the-daggers-sharp-%EF%B8%8F-230b3191c3f#a530

TL;DR: For memory efficiency it is better to scope the service/repository/whatever per the actual scope you need it - as I've done with `SomeService` that is scoped to `@ActivityScope`.
